### PR TITLE
Fix deprecation warnings and drop support for Django 1.11

### PR DESCRIPTION
**Pull request by mscansian**
- Sets a default_auto_field [Django 3.2](https://docs.djangoproject.com/en/3.2/releases/3.2/#automatic-appconfig-discovery)
- Fix `django.conf.urls` deprecation warnings [Django 2.0](https://docs.djangoproject.com/en/dev/releases/2.0/#what-s-new-in-django-2-0)
- Drop support for Django 1.11

# Dropping support for Django 1.11
The changes made to `django.conf.urls` are not compatible with Django 1.11. With the release of Django 4.0 (which will happen any time soon), `django.conf.urls` [will be removed](https://docs.djangoproject.com/en/3.2/internals/deprecation/#deprecation-removed-in-4-0) leaving users with a broken dependency (in case we don't fix it).

### CODE REVIEW

**Comment by stinovlas** [comment]
`isort` in `quality` check is failing. Other than that, I agree. LGTM

**Comment by mscansian** [comment]
> `isort` in `quality` check is failing. Other than that, I agree. LGTM

Fixed

@stinovlas @tpazderka

**Review by stinovlas — APPROVED** [review]

**Comment by stinovlas** [comment]
@tpazderka LGTM. If you're OK with this as well, please merge the PR.

@mscansian Thanks for the contribution :-)!

**Comment by tpazderka** [comment]
Rebased and merged.

@mscansian Thanks for the contrbuition!

**Comment by mscansian** [comment]
@tpazderka Hey, is it possible to release the changes to PyPI?

**Comment by tpazderka** [comment]
We need to deal with #146 first as the `master` branch is currently broken for existing users.

**Pull request closed without merging**
